[book]
authors = ["JordiMateoUdL"]
language = "ca"
multilingual = false
src = "src"
title = "Laboratoris d'Administraci√≥ i Manteniment de Sistemes i Aplicacions"

[output.html.code.highlight]
bash = "~"